version: '3.5'

services:
  provider:
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - golem-provider:/root/
    devices:
      - /dev/kvm:/dev/kvm
    env_file:
      - .env